name: Node CI

on: [push]

jobs:
    
  build:

    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379
      mongodb:
        image: mongo
        ports: 
          - 27017

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
    - run: redis-cli ping
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: start redis
      run: redis-server
    - name: npm install, build, and test
      run: |
        npm install
        npm run dev
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.CIELTOKEN }}
